[project]
name = "scaldys"
version = "0.2.2"
authors = [
  { name="scaldys", email="scaldys@scaldys.net" },
]
description = "A skeleton for Python projects by Scaldys."
readme = "README.rst"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
]
license-files = ["LICEN[CS]E*"]
dependencies = [
    "art>=6.5",
    "platformdirs>=4.9.6",
    "pydantic-settings>=2.0",
    "typer>=0.25.0",
]

[project.scripts]
scaldys = "scaldys.cli.cli:app"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["scaldys*"]

[dependency-groups]
dev = [
    "scaldys-builder[cython,windows,docs]",
    "pre-commit>=4.5.0",
    "pyright>=1.1.409",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.12",
    "sphinx>=9.1.0",
    "sphinx-rtd-theme>=3.1.0",
]

[tool.uv.sources]
scaldys-builder = { path = "../scaldys-builder", editable = true }

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]

[tool.pyright]
exclude = [".venv"]
pythonVersion = "3.13"
venvPath = "."
venv = ".venv"

#[[tool.uv.index]]
#name = "testpypi"
#url = "https://test.pypi.org/simple/"
#publish-url = "https://test.pypi.org/legacy/"
