"""
Main entry point for the Scaldys build system.

This script provides a unified CLI for building the project across different
platforms. Currently, it supports Windows builds (documentation, executables,
and installers).
"""

import logging
import tomllib
from pathlib import Path
import typer
from rich.console import Console
from rich.logging import RichHandler

from scaldys_builder.windows.builder import WindowsBuilder

PROJECT_ROOT = Path(__file__).resolve().parent.parent

with open(PROJECT_ROOT / "pyproject.toml", "rb") as _f:
    _APP_NAME = tomllib.load(_f)["project"]["name"].capitalize()

# Configure logging
console = Console()
logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    datefmt="[%X]",
    handlers=[RichHandler(rich_tracebacks=True, console=console, show_path=False, markup=True)],
)
logger = logging.getLogger(__name__)

app = typer.Typer(help=f"{_APP_NAME} Build Tool", no_args_is_help=True)
build_app = typer.Typer(help="Build subcommands", no_args_is_help=True)
windows_app = typer.Typer(help="Windows specific build subcommands", no_args_is_help=True)

app.add_typer(build_app, name="build")
build_app.add_typer(windows_app, name="windows")


@windows_app.command("docs")
def windows_docs(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Build Windows documentation."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.env.pre_flight_checks(require_sphinx=True)
    builder.build_docs()


@windows_app.command("exe")
def windows_exe(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Build Windows executables."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.build_exe()


@windows_app.command("installer")
def windows_installer(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Build Windows setup installer."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.build_installer()


@windows_app.command("all")
def windows_all(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Run the complete end-to-end Windows build workflow."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.main(console=console)


@windows_app.command("clean")
def windows_clean(
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    """Clean out files generated by previous build."""
    builder = WindowsBuilder(PROJECT_ROOT, verbose=verbose)
    builder.clean()


if __name__ == "__main__":
    app()
