# CI setup
# Lint, format code and documentation, check type consistency, run tests with coverage and build
name: Python Code Quality

on:
  pull_request:
  push:

jobs:
  code_quality:
    name: Lint, format and type consistency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - name: UV verify lock file
        run: uv lock --locked

      - name: Ruff lint
        run: uv run ruff check .

      - name: Ruff format
        run: uv run ruff format --diff .

      # This isn't a general Python lint, this style is just used in this repository
      - name: Prettier format
        run: npx prettier --prose-wrap always --check "**/*.md"

      - name: PyRight type consistency
        run: uv run pyright ./src

  test:
    name: Run tests
    needs: [code_quality]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - run: uv run pytest -v --durations=0 --cov --cov-report=xml

  build:
    name: Build the project
    needs: [code_quality, test]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - run: uv build